org: gian2030rosexp
service: api-web-scraping

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::153620185912:role/LabRole

functions:
  scrape_table:
    handler: scrape_table.lambda_handler
    package:
      include:
        - scrape_table.py
    events:
      - http:
          path: /scrape/table
          method: get
          cors: true

resources:
  Resources:
    TablaWebScrapping:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaWebScrapping
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
